# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e7842fe5b9f9cb7be8f74260503f5395e810dd02c14521caf37cdf8637cd0156a3cb6a64f45d058e28c3b759a471e60c06733b1badd7d9648ca9ebd47ce524e

test:
  secret_key_base: 30561f7419a161e56ac9ddfbc872946bb457ae02012e3543b19f5abc36b483cde758528d45836d808986fca8c6437a2f386bdcc1d938a3e14e5238e495d7686c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
